name: first

on: 
  push:
    branches:
      - main


jobs:
  build_ubuntu:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v4
      - name: compile_go_file
        run: go build -o main main.go
      - name: run_go_file
        run: ./main        
  build_windows:
    name: build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v4
      - name: compile_go_file
        run: go build -o main.exe main.go
      - name: run_go_file
        run: .\main.exe
  build_macos:
    name: build
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v4
      - name: compile_go_file
        run: go build -o main main.go
      - name: run_go_file
        run: ./main
  build_crossplatform:
    name: build
    runs-on: ubuntu-latest
    needs: [build_ubuntu, build_windows, build_macos]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.22'
      - name: crosscompile_go_file
        run: |
          echo "Cross compiling for all  platforms"
          GOOS=windows GOARCH=amd64 go build -o main.exe main.go
          GOOS=linux GOARCH=amd64 go build -o main main.go
          GOOS=darwin GOARCH=amd64 go build -o main main.go